# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UFT_Ui.ui'
#
# Created: Tue Nov 07 14:01:07 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(970, 770)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 951, 701))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_EB1 = QtGui.QWidget()
        self.tab_EB1.setObjectName(_fromUtf8("tab_EB1"))
        self.groupBox1_8 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_8.setGeometry(QtCore.QRect(10, 590, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_8.sizePolicy().hasHeightForWidth())
        self.groupBox1_8.setSizePolicy(sizePolicy)
        self.groupBox1_8.setObjectName(_fromUtf8("groupBox1_8"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox1_8)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.sn_lineEdit_1_8 = QtGui.QLineEdit(self.groupBox1_8)
        self.sn_lineEdit_1_8.setMaxLength(33)
        self.sn_lineEdit_1_8.setObjectName(_fromUtf8("sn_lineEdit_1_8"))
        self.gridLayout_11.addWidget(self.sn_lineEdit_1_8, 0, 0, 1, 1)
        self.CablelineEdit_1_8 = QtGui.QLineEdit(self.groupBox1_8)
        self.CablelineEdit_1_8.setObjectName(_fromUtf8("CablelineEdit_1_8"))
        self.gridLayout_11.addWidget(self.CablelineEdit_1_8, 0, 1, 1, 1)
        self.label_1_8 = QtGui.QLabel(self.groupBox1_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_8.setFont(font)
        self.label_1_8.setText(_fromUtf8(""))
        self.label_1_8.setObjectName(_fromUtf8("label_1_8"))
        self.gridLayout_11.addWidget(self.label_1_8, 1, 0, 1, 1)
        self.BatterylineEdit_1_8 = QtGui.QLineEdit(self.groupBox1_8)
        self.BatterylineEdit_1_8.setObjectName(_fromUtf8("BatterylineEdit_1_8"))
        self.gridLayout_11.addWidget(self.BatterylineEdit_1_8, 1, 1, 1, 1)
        self.groupBox1_2 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_2.setGeometry(QtCore.QRect(10, 90, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_2.sizePolicy().hasHeightForWidth())
        self.groupBox1_2.setSizePolicy(sizePolicy)
        self.groupBox1_2.setObjectName(_fromUtf8("groupBox1_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox1_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sn_lineEdit_1_2 = QtGui.QLineEdit(self.groupBox1_2)
        self.sn_lineEdit_1_2.setMaxLength(33)
        self.sn_lineEdit_1_2.setObjectName(_fromUtf8("sn_lineEdit_1_2"))
        self.gridLayout_2.addWidget(self.sn_lineEdit_1_2, 0, 0, 1, 1)
        self.CablelineEdit_1_2 = QtGui.QLineEdit(self.groupBox1_2)
        self.CablelineEdit_1_2.setObjectName(_fromUtf8("CablelineEdit_1_2"))
        self.gridLayout_2.addWidget(self.CablelineEdit_1_2, 0, 1, 1, 1)
        self.label_1_2 = QtGui.QLabel(self.groupBox1_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_2.setFont(font)
        self.label_1_2.setText(_fromUtf8(""))
        self.label_1_2.setObjectName(_fromUtf8("label_1_2"))
        self.gridLayout_2.addWidget(self.label_1_2, 1, 0, 1, 1)
        self.BatterylineEdit_1_2 = QtGui.QLineEdit(self.groupBox1_2)
        self.BatterylineEdit_1_2.setObjectName(_fromUtf8("BatterylineEdit_1_2"))
        self.gridLayout_2.addWidget(self.BatterylineEdit_1_2, 1, 1, 1, 1)
        self.groupBox1_3 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_3.setGeometry(QtCore.QRect(10, 170, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_3.sizePolicy().hasHeightForWidth())
        self.groupBox1_3.setSizePolicy(sizePolicy)
        self.groupBox1_3.setObjectName(_fromUtf8("groupBox1_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox1_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.sn_lineEdit_1_3 = QtGui.QLineEdit(self.groupBox1_3)
        self.sn_lineEdit_1_3.setMaxLength(33)
        self.sn_lineEdit_1_3.setObjectName(_fromUtf8("sn_lineEdit_1_3"))
        self.gridLayout_3.addWidget(self.sn_lineEdit_1_3, 0, 0, 1, 1)
        self.CablelineEdit_1_3 = QtGui.QLineEdit(self.groupBox1_3)
        self.CablelineEdit_1_3.setObjectName(_fromUtf8("CablelineEdit_1_3"))
        self.gridLayout_3.addWidget(self.CablelineEdit_1_3, 0, 1, 1, 1)
        self.label_1_3 = QtGui.QLabel(self.groupBox1_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_3.setFont(font)
        self.label_1_3.setText(_fromUtf8(""))
        self.label_1_3.setObjectName(_fromUtf8("label_1_3"))
        self.gridLayout_3.addWidget(self.label_1_3, 1, 0, 1, 1)
        self.BatterylineEdit_1_3 = QtGui.QLineEdit(self.groupBox1_3)
        self.BatterylineEdit_1_3.setObjectName(_fromUtf8("BatterylineEdit_1_3"))
        self.gridLayout_3.addWidget(self.BatterylineEdit_1_3, 1, 1, 1, 1)
        self.groupBox1_4 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_4.setGeometry(QtCore.QRect(10, 250, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_4.sizePolicy().hasHeightForWidth())
        self.groupBox1_4.setSizePolicy(sizePolicy)
        self.groupBox1_4.setObjectName(_fromUtf8("groupBox1_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox1_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.sn_lineEdit_1_4 = QtGui.QLineEdit(self.groupBox1_4)
        self.sn_lineEdit_1_4.setMaxLength(33)
        self.sn_lineEdit_1_4.setObjectName(_fromUtf8("sn_lineEdit_1_4"))
        self.gridLayout_6.addWidget(self.sn_lineEdit_1_4, 0, 0, 1, 1)
        self.CablelineEdit_1_4 = QtGui.QLineEdit(self.groupBox1_4)
        self.CablelineEdit_1_4.setObjectName(_fromUtf8("CablelineEdit_1_4"))
        self.gridLayout_6.addWidget(self.CablelineEdit_1_4, 0, 1, 1, 1)
        self.label_1_4 = QtGui.QLabel(self.groupBox1_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_4.setFont(font)
        self.label_1_4.setText(_fromUtf8(""))
        self.label_1_4.setObjectName(_fromUtf8("label_1_4"))
        self.gridLayout_6.addWidget(self.label_1_4, 1, 0, 1, 1)
        self.BatterylineEdit_1_4 = QtGui.QLineEdit(self.groupBox1_4)
        self.BatterylineEdit_1_4.setObjectName(_fromUtf8("BatterylineEdit_1_4"))
        self.gridLayout_6.addWidget(self.BatterylineEdit_1_4, 1, 1, 1, 1)
        self.groupBox1_5 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_5.setGeometry(QtCore.QRect(10, 350, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_5.sizePolicy().hasHeightForWidth())
        self.groupBox1_5.setSizePolicy(sizePolicy)
        self.groupBox1_5.setObjectName(_fromUtf8("groupBox1_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox1_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.sn_lineEdit_1_5 = QtGui.QLineEdit(self.groupBox1_5)
        self.sn_lineEdit_1_5.setAcceptDrops(True)
        self.sn_lineEdit_1_5.setText(_fromUtf8(""))
        self.sn_lineEdit_1_5.setMaxLength(33)
        self.sn_lineEdit_1_5.setObjectName(_fromUtf8("sn_lineEdit_1_5"))
        self.gridLayout_7.addWidget(self.sn_lineEdit_1_5, 0, 0, 1, 1)
        self.CablelineEdit_1_5 = QtGui.QLineEdit(self.groupBox1_5)
        self.CablelineEdit_1_5.setObjectName(_fromUtf8("CablelineEdit_1_5"))
        self.gridLayout_7.addWidget(self.CablelineEdit_1_5, 0, 1, 1, 1)
        self.label_1_5 = QtGui.QLabel(self.groupBox1_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_5.setFont(font)
        self.label_1_5.setText(_fromUtf8(""))
        self.label_1_5.setObjectName(_fromUtf8("label_1_5"))
        self.gridLayout_7.addWidget(self.label_1_5, 1, 0, 1, 1)
        self.BatterylineEdit_1_5 = QtGui.QLineEdit(self.groupBox1_5)
        self.BatterylineEdit_1_5.setObjectName(_fromUtf8("BatterylineEdit_1_5"))
        self.gridLayout_7.addWidget(self.BatterylineEdit_1_5, 1, 1, 1, 1)
        self.groupBox1_6 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_6.setGeometry(QtCore.QRect(10, 430, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_6.sizePolicy().hasHeightForWidth())
        self.groupBox1_6.setSizePolicy(sizePolicy)
        self.groupBox1_6.setObjectName(_fromUtf8("groupBox1_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox1_6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.sn_lineEdit_1_6 = QtGui.QLineEdit(self.groupBox1_6)
        self.sn_lineEdit_1_6.setMaxLength(33)
        self.sn_lineEdit_1_6.setObjectName(_fromUtf8("sn_lineEdit_1_6"))
        self.gridLayout_8.addWidget(self.sn_lineEdit_1_6, 0, 0, 1, 1)
        self.CablelineEdit_1_6 = QtGui.QLineEdit(self.groupBox1_6)
        self.CablelineEdit_1_6.setObjectName(_fromUtf8("CablelineEdit_1_6"))
        self.gridLayout_8.addWidget(self.CablelineEdit_1_6, 0, 1, 1, 1)
        self.label_1_6 = QtGui.QLabel(self.groupBox1_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_6.setFont(font)
        self.label_1_6.setText(_fromUtf8(""))
        self.label_1_6.setObjectName(_fromUtf8("label_1_6"))
        self.gridLayout_8.addWidget(self.label_1_6, 1, 0, 1, 1)
        self.BatterylineEdit_1_6 = QtGui.QLineEdit(self.groupBox1_6)
        self.BatterylineEdit_1_6.setObjectName(_fromUtf8("BatterylineEdit_1_6"))
        self.gridLayout_8.addWidget(self.BatterylineEdit_1_6, 1, 1, 1, 1)
        self.groupBox1_1 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_1.setGeometry(QtCore.QRect(10, 10, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_1.sizePolicy().hasHeightForWidth())
        self.groupBox1_1.setSizePolicy(sizePolicy)
        self.groupBox1_1.setObjectName(_fromUtf8("groupBox1_1"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox1_1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sn_lineEdit_1_1 = QtGui.QLineEdit(self.groupBox1_1)
        self.sn_lineEdit_1_1.setAcceptDrops(True)
        self.sn_lineEdit_1_1.setText(_fromUtf8(""))
        self.sn_lineEdit_1_1.setMaxLength(33)
        self.sn_lineEdit_1_1.setObjectName(_fromUtf8("sn_lineEdit_1_1"))
        self.gridLayout.addWidget(self.sn_lineEdit_1_1, 0, 0, 1, 1)
        self.CablelineEdit_1_1 = QtGui.QLineEdit(self.groupBox1_1)
        self.CablelineEdit_1_1.setObjectName(_fromUtf8("CablelineEdit_1_1"))
        self.gridLayout.addWidget(self.CablelineEdit_1_1, 0, 1, 1, 1)
        self.label_1_1 = QtGui.QLabel(self.groupBox1_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_1.setFont(font)
        self.label_1_1.setText(_fromUtf8(""))
        self.label_1_1.setObjectName(_fromUtf8("label_1_1"))
        self.gridLayout.addWidget(self.label_1_1, 1, 0, 1, 1)
        self.BatterylineEdit_1_1 = QtGui.QLineEdit(self.groupBox1_1)
        self.BatterylineEdit_1_1.setObjectName(_fromUtf8("BatterylineEdit_1_1"))
        self.gridLayout.addWidget(self.BatterylineEdit_1_1, 1, 1, 1, 1)
        self.groupBox1_7 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_7.setGeometry(QtCore.QRect(10, 510, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_7.sizePolicy().hasHeightForWidth())
        self.groupBox1_7.setSizePolicy(sizePolicy)
        self.groupBox1_7.setObjectName(_fromUtf8("groupBox1_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox1_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.sn_lineEdit_1_7 = QtGui.QLineEdit(self.groupBox1_7)
        self.sn_lineEdit_1_7.setMaxLength(33)
        self.sn_lineEdit_1_7.setObjectName(_fromUtf8("sn_lineEdit_1_7"))
        self.gridLayout_10.addWidget(self.sn_lineEdit_1_7, 0, 0, 1, 1)
        self.CablelineEdit_1_7 = QtGui.QLineEdit(self.groupBox1_7)
        self.CablelineEdit_1_7.setObjectName(_fromUtf8("CablelineEdit_1_7"))
        self.gridLayout_10.addWidget(self.CablelineEdit_1_7, 0, 1, 1, 1)
        self.label_1_7 = QtGui.QLabel(self.groupBox1_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_7.setFont(font)
        self.label_1_7.setText(_fromUtf8(""))
        self.label_1_7.setObjectName(_fromUtf8("label_1_7"))
        self.gridLayout_10.addWidget(self.label_1_7, 1, 0, 1, 1)
        self.BatterylineEdit_1_7 = QtGui.QLineEdit(self.groupBox1_7)
        self.BatterylineEdit_1_7.setObjectName(_fromUtf8("BatterylineEdit_1_7"))
        self.gridLayout_10.addWidget(self.BatterylineEdit_1_7, 1, 1, 1, 1)
        self.groupBox1_16 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_16.setGeometry(QtCore.QRect(480, 590, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_16.sizePolicy().hasHeightForWidth())
        self.groupBox1_16.setSizePolicy(sizePolicy)
        self.groupBox1_16.setObjectName(_fromUtf8("groupBox1_16"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox1_16)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.sn_lineEdit_1_16 = QtGui.QLineEdit(self.groupBox1_16)
        self.sn_lineEdit_1_16.setMaxLength(33)
        self.sn_lineEdit_1_16.setObjectName(_fromUtf8("sn_lineEdit_1_16"))
        self.gridLayout_19.addWidget(self.sn_lineEdit_1_16, 0, 0, 1, 1)
        self.CablelineEdit_1_16 = QtGui.QLineEdit(self.groupBox1_16)
        self.CablelineEdit_1_16.setObjectName(_fromUtf8("CablelineEdit_1_16"))
        self.gridLayout_19.addWidget(self.CablelineEdit_1_16, 0, 1, 1, 1)
        self.label_1_16 = QtGui.QLabel(self.groupBox1_16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_16.setFont(font)
        self.label_1_16.setText(_fromUtf8(""))
        self.label_1_16.setObjectName(_fromUtf8("label_1_16"))
        self.gridLayout_19.addWidget(self.label_1_16, 1, 0, 1, 1)
        self.BatterylineEdit_1_16 = QtGui.QLineEdit(self.groupBox1_16)
        self.BatterylineEdit_1_16.setObjectName(_fromUtf8("BatterylineEdit_1_16"))
        self.gridLayout_19.addWidget(self.BatterylineEdit_1_16, 1, 1, 1, 1)
        self.groupBox1_9 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_9.setGeometry(QtCore.QRect(480, 10, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_9.sizePolicy().hasHeightForWidth())
        self.groupBox1_9.setSizePolicy(sizePolicy)
        self.groupBox1_9.setObjectName(_fromUtf8("groupBox1_9"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox1_9)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.sn_lineEdit_1_9 = QtGui.QLineEdit(self.groupBox1_9)
        self.sn_lineEdit_1_9.setAcceptDrops(True)
        self.sn_lineEdit_1_9.setText(_fromUtf8(""))
        self.sn_lineEdit_1_9.setMaxLength(33)
        self.sn_lineEdit_1_9.setObjectName(_fromUtf8("sn_lineEdit_1_9"))
        self.gridLayout_12.addWidget(self.sn_lineEdit_1_9, 0, 0, 1, 1)
        self.CablelineEdit_1_9 = QtGui.QLineEdit(self.groupBox1_9)
        self.CablelineEdit_1_9.setObjectName(_fromUtf8("CablelineEdit_1_9"))
        self.gridLayout_12.addWidget(self.CablelineEdit_1_9, 0, 1, 1, 1)
        self.label_1_9 = QtGui.QLabel(self.groupBox1_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_9.setFont(font)
        self.label_1_9.setText(_fromUtf8(""))
        self.label_1_9.setObjectName(_fromUtf8("label_1_9"))
        self.gridLayout_12.addWidget(self.label_1_9, 1, 0, 1, 1)
        self.BatterylineEdit_1_9 = QtGui.QLineEdit(self.groupBox1_9)
        self.BatterylineEdit_1_9.setObjectName(_fromUtf8("BatterylineEdit_1_9"))
        self.gridLayout_12.addWidget(self.BatterylineEdit_1_9, 1, 1, 1, 1)
        self.groupBox1_11 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_11.setGeometry(QtCore.QRect(480, 170, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_11.sizePolicy().hasHeightForWidth())
        self.groupBox1_11.setSizePolicy(sizePolicy)
        self.groupBox1_11.setObjectName(_fromUtf8("groupBox1_11"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox1_11)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.sn_lineEdit_1_11 = QtGui.QLineEdit(self.groupBox1_11)
        self.sn_lineEdit_1_11.setMaxLength(33)
        self.sn_lineEdit_1_11.setObjectName(_fromUtf8("sn_lineEdit_1_11"))
        self.gridLayout_14.addWidget(self.sn_lineEdit_1_11, 0, 0, 1, 1)
        self.CablelineEdit_1_11 = QtGui.QLineEdit(self.groupBox1_11)
        self.CablelineEdit_1_11.setObjectName(_fromUtf8("CablelineEdit_1_11"))
        self.gridLayout_14.addWidget(self.CablelineEdit_1_11, 0, 1, 1, 1)
        self.label_1_11 = QtGui.QLabel(self.groupBox1_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_11.setFont(font)
        self.label_1_11.setText(_fromUtf8(""))
        self.label_1_11.setObjectName(_fromUtf8("label_1_11"))
        self.gridLayout_14.addWidget(self.label_1_11, 1, 0, 1, 1)
        self.BatterylineEdit_1_11 = QtGui.QLineEdit(self.groupBox1_11)
        self.BatterylineEdit_1_11.setObjectName(_fromUtf8("BatterylineEdit_1_11"))
        self.gridLayout_14.addWidget(self.BatterylineEdit_1_11, 1, 1, 1, 1)
        self.groupBox1_12 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_12.setGeometry(QtCore.QRect(480, 250, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_12.sizePolicy().hasHeightForWidth())
        self.groupBox1_12.setSizePolicy(sizePolicy)
        self.groupBox1_12.setObjectName(_fromUtf8("groupBox1_12"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox1_12)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.sn_lineEdit_1_12 = QtGui.QLineEdit(self.groupBox1_12)
        self.sn_lineEdit_1_12.setMaxLength(33)
        self.sn_lineEdit_1_12.setObjectName(_fromUtf8("sn_lineEdit_1_12"))
        self.gridLayout_15.addWidget(self.sn_lineEdit_1_12, 0, 0, 1, 1)
        self.CablelineEdit_1_12 = QtGui.QLineEdit(self.groupBox1_12)
        self.CablelineEdit_1_12.setObjectName(_fromUtf8("CablelineEdit_1_12"))
        self.gridLayout_15.addWidget(self.CablelineEdit_1_12, 0, 1, 1, 1)
        self.label_1_12 = QtGui.QLabel(self.groupBox1_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_12.setFont(font)
        self.label_1_12.setText(_fromUtf8(""))
        self.label_1_12.setObjectName(_fromUtf8("label_1_12"))
        self.gridLayout_15.addWidget(self.label_1_12, 1, 0, 1, 1)
        self.BatterylineEdit_1_12 = QtGui.QLineEdit(self.groupBox1_12)
        self.BatterylineEdit_1_12.setObjectName(_fromUtf8("BatterylineEdit_1_12"))
        self.gridLayout_15.addWidget(self.BatterylineEdit_1_12, 1, 1, 1, 1)
        self.groupBox1_13 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_13.setGeometry(QtCore.QRect(480, 350, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_13.sizePolicy().hasHeightForWidth())
        self.groupBox1_13.setSizePolicy(sizePolicy)
        self.groupBox1_13.setObjectName(_fromUtf8("groupBox1_13"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox1_13)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.sn_lineEdit_1_13 = QtGui.QLineEdit(self.groupBox1_13)
        self.sn_lineEdit_1_13.setAcceptDrops(True)
        self.sn_lineEdit_1_13.setText(_fromUtf8(""))
        self.sn_lineEdit_1_13.setMaxLength(33)
        self.sn_lineEdit_1_13.setObjectName(_fromUtf8("sn_lineEdit_1_13"))
        self.gridLayout_16.addWidget(self.sn_lineEdit_1_13, 0, 0, 1, 1)
        self.CablelineEdit_1_13 = QtGui.QLineEdit(self.groupBox1_13)
        self.CablelineEdit_1_13.setObjectName(_fromUtf8("CablelineEdit_1_13"))
        self.gridLayout_16.addWidget(self.CablelineEdit_1_13, 0, 1, 1, 1)
        self.label_1_13 = QtGui.QLabel(self.groupBox1_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_13.setFont(font)
        self.label_1_13.setText(_fromUtf8(""))
        self.label_1_13.setObjectName(_fromUtf8("label_1_13"))
        self.gridLayout_16.addWidget(self.label_1_13, 1, 0, 1, 1)
        self.BatterylineEdit_1_13 = QtGui.QLineEdit(self.groupBox1_13)
        self.BatterylineEdit_1_13.setObjectName(_fromUtf8("BatterylineEdit_1_13"))
        self.gridLayout_16.addWidget(self.BatterylineEdit_1_13, 1, 1, 1, 1)
        self.groupBox1_10 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_10.setGeometry(QtCore.QRect(480, 90, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_10.sizePolicy().hasHeightForWidth())
        self.groupBox1_10.setSizePolicy(sizePolicy)
        self.groupBox1_10.setObjectName(_fromUtf8("groupBox1_10"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox1_10)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.sn_lineEdit_1_10 = QtGui.QLineEdit(self.groupBox1_10)
        self.sn_lineEdit_1_10.setMaxLength(33)
        self.sn_lineEdit_1_10.setObjectName(_fromUtf8("sn_lineEdit_1_10"))
        self.gridLayout_13.addWidget(self.sn_lineEdit_1_10, 0, 0, 1, 1)
        self.CablelineEdit_1_10 = QtGui.QLineEdit(self.groupBox1_10)
        self.CablelineEdit_1_10.setObjectName(_fromUtf8("CablelineEdit_1_10"))
        self.gridLayout_13.addWidget(self.CablelineEdit_1_10, 0, 1, 1, 1)
        self.label_1_10 = QtGui.QLabel(self.groupBox1_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_10.setFont(font)
        self.label_1_10.setText(_fromUtf8(""))
        self.label_1_10.setObjectName(_fromUtf8("label_1_10"))
        self.gridLayout_13.addWidget(self.label_1_10, 1, 0, 1, 1)
        self.BatterylineEdit_1_10 = QtGui.QLineEdit(self.groupBox1_10)
        self.BatterylineEdit_1_10.setObjectName(_fromUtf8("BatterylineEdit_1_10"))
        self.gridLayout_13.addWidget(self.BatterylineEdit_1_10, 1, 1, 1, 1)
        self.groupBox1_14 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_14.setGeometry(QtCore.QRect(480, 430, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_14.sizePolicy().hasHeightForWidth())
        self.groupBox1_14.setSizePolicy(sizePolicy)
        self.groupBox1_14.setObjectName(_fromUtf8("groupBox1_14"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox1_14)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.sn_lineEdit_1_14 = QtGui.QLineEdit(self.groupBox1_14)
        self.sn_lineEdit_1_14.setMaxLength(33)
        self.sn_lineEdit_1_14.setObjectName(_fromUtf8("sn_lineEdit_1_14"))
        self.gridLayout_17.addWidget(self.sn_lineEdit_1_14, 0, 0, 1, 1)
        self.CablelineEdit_1_14 = QtGui.QLineEdit(self.groupBox1_14)
        self.CablelineEdit_1_14.setObjectName(_fromUtf8("CablelineEdit_1_14"))
        self.gridLayout_17.addWidget(self.CablelineEdit_1_14, 0, 1, 1, 1)
        self.label_1_14 = QtGui.QLabel(self.groupBox1_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_14.setFont(font)
        self.label_1_14.setText(_fromUtf8(""))
        self.label_1_14.setObjectName(_fromUtf8("label_1_14"))
        self.gridLayout_17.addWidget(self.label_1_14, 1, 0, 1, 1)
        self.BatterylineEdit_1_14 = QtGui.QLineEdit(self.groupBox1_14)
        self.BatterylineEdit_1_14.setObjectName(_fromUtf8("BatterylineEdit_1_14"))
        self.gridLayout_17.addWidget(self.BatterylineEdit_1_14, 1, 1, 1, 1)
        self.groupBox1_15 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1_15.setGeometry(QtCore.QRect(480, 510, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1_15.sizePolicy().hasHeightForWidth())
        self.groupBox1_15.setSizePolicy(sizePolicy)
        self.groupBox1_15.setObjectName(_fromUtf8("groupBox1_15"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox1_15)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.sn_lineEdit_1_15 = QtGui.QLineEdit(self.groupBox1_15)
        self.sn_lineEdit_1_15.setMaxLength(33)
        self.sn_lineEdit_1_15.setObjectName(_fromUtf8("sn_lineEdit_1_15"))
        self.gridLayout_18.addWidget(self.sn_lineEdit_1_15, 0, 0, 1, 1)
        self.CablelineEdit_1_15 = QtGui.QLineEdit(self.groupBox1_15)
        self.CablelineEdit_1_15.setObjectName(_fromUtf8("CablelineEdit_1_15"))
        self.gridLayout_18.addWidget(self.CablelineEdit_1_15, 0, 1, 1, 1)
        self.label_1_15 = QtGui.QLabel(self.groupBox1_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_15.setFont(font)
        self.label_1_15.setText(_fromUtf8(""))
        self.label_1_15.setObjectName(_fromUtf8("label_1_15"))
        self.gridLayout_18.addWidget(self.label_1_15, 1, 0, 1, 1)
        self.BatterylineEdit_1_15 = QtGui.QLineEdit(self.groupBox1_15)
        self.BatterylineEdit_1_15.setObjectName(_fromUtf8("BatterylineEdit_1_15"))
        self.gridLayout_18.addWidget(self.BatterylineEdit_1_15, 1, 1, 1, 1)
        self.line = QtGui.QFrame(self.tab_EB1)
        self.line.setGeometry(QtCore.QRect(10, 330, 921, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab_EB1)
        self.line_2.setGeometry(QtCore.QRect(460, 20, 20, 651))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tabWidget.addTab(self.tab_EB1, _fromUtf8(""))
        self.tab_EB2 = QtGui.QWidget()
        self.tab_EB2.setObjectName(_fromUtf8("tab_EB2"))
        self.tabWidget.addTab(self.tab_EB2, _fromUtf8(""))
        self.tab_EB3 = QtGui.QWidget()
        self.tab_EB3.setObjectName(_fromUtf8("tab_EB3"))
        self.tabWidget.addTab(self.tab_EB3, _fromUtf8(""))
        self.tab_EB4 = QtGui.QWidget()
        self.tab_EB4.setObjectName(_fromUtf8("tab_EB4"))
        self.tabWidget.addTab(self.tab_EB4, _fromUtf8(""))
        self.info = QtGui.QWidget()
        self.info.setObjectName(_fromUtf8("info"))
        self.groupBox_6 = QtGui.QGroupBox(self.info)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 931, 661))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.info_textBrowser = QtGui.QTextBrowser(self.groupBox_6)
        self.info_textBrowser.setGeometry(QtCore.QRect(10, 20, 911, 631))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_textBrowser.sizePolicy().hasHeightForWidth())
        self.info_textBrowser.setSizePolicy(sizePolicy)
        self.info_textBrowser.setAutoFillBackground(True)
        self.info_textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.info_textBrowser.setObjectName(_fromUtf8("info_textBrowser"))
        self.tabWidget.addTab(self.info, _fromUtf8(""))
        self.configuration = QtGui.QWidget()
        self.configuration.setObjectName(_fromUtf8("configuration"))
        self.gridLayout_9 = QtGui.QGridLayout(self.configuration)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.partNum_comboBox = QtGui.QComboBox(self.configuration)
        self.partNum_comboBox.setObjectName(_fromUtf8("partNum_comboBox"))
        self.gridLayout_4.addWidget(self.partNum_comboBox, 1, 0, 1, 1)
        self.label_PN = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_PN.setFont(font)
        self.label_PN.setObjectName(_fromUtf8("label_PN"))
        self.gridLayout_4.addWidget(self.label_PN, 0, 0, 1, 1)
        self.label_REV = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_REV.setFont(font)
        self.label_REV.setObjectName(_fromUtf8("label_REV"))
        self.gridLayout_4.addWidget(self.label_REV, 0, 1, 1, 1)
        self.revision_comboBox = QtGui.QComboBox(self.configuration)
        self.revision_comboBox.setObjectName(_fromUtf8("revision_comboBox"))
        self.gridLayout_4.addWidget(self.revision_comboBox, 1, 1, 1, 1)
        self.label_DES = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label_DES.setFont(font)
        self.label_DES.setObjectName(_fromUtf8("label_DES"))
        self.gridLayout_4.addWidget(self.label_DES, 0, 2, 1, 1)
        self.descriptionLabel = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setText(_fromUtf8(""))
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.gridLayout_4.addWidget(self.descriptionLabel, 1, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.test_item_tableView = QtGui.QTableView(self.configuration)
        self.test_item_tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.test_item_tableView.setObjectName(_fromUtf8("test_item_tableView"))
        self.gridLayout_9.addWidget(self.test_item_tableView, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.submit_pushButton = QtGui.QPushButton(self.configuration)
        self.submit_pushButton.setEnabled(False)
        self.submit_pushButton.setObjectName(_fromUtf8("submit_pushButton"))
        self.horizontalLayout_5.addWidget(self.submit_pushButton)
        self.checkBox = QtGui.QCheckBox(self.configuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.tabWidget.addTab(self.configuration, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.search_lineEdit = QtGui.QLineEdit(self.tab)
        self.search_lineEdit.setInputMask(_fromUtf8(""))
        self.search_lineEdit.setObjectName(_fromUtf8("search_lineEdit"))
        self.horizontalLayout_2.addWidget(self.search_lineEdit)
        self.search_pushButton = QtGui.QPushButton(self.tab)
        self.search_pushButton.setObjectName(_fromUtf8("search_pushButton"))
        self.horizontalLayout_2.addWidget(self.search_pushButton)
        self.search_result_label = QtGui.QLabel(self.tab)
        self.search_result_label.setText(_fromUtf8(""))
        self.search_result_label.setObjectName(_fromUtf8("search_result_label"))
        self.horizontalLayout_2.addWidget(self.search_result_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.log_tableView = QtGui.QTableView(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_tableView.sizePolicy().hasHeightForWidth())
        self.log_tableView.setSizePolicy(sizePolicy)
        self.log_tableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.log_tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.log_tableView.setObjectName(_fromUtf8("log_tableView"))
        self.gridLayout_5.addWidget(self.log_tableView, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.title_label = QtGui.QLabel(Form)
        self.title_label.setGeometry(QtCore.QRect(20, 5, 311, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andalus"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAutoFillBackground(False)
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 740, 951, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.lcdNumber = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout_4.addWidget(self.lcdNumber)
        self.start_pushButton = QtGui.QPushButton(Form)
        self.start_pushButton.setGeometry(QtCore.QRect(750, 5, 161, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_pushButton.sizePolicy().hasHeightForWidth())
        self.start_pushButton.setSizePolicy(sizePolicy)
        self.start_pushButton.setObjectName(_fromUtf8("start_pushButton"))
        self.Mode4in1 = QtGui.QCheckBox(Form)
        self.Mode4in1.setGeometry(QtCore.QRect(580, 30, 67, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mode4in1.sizePolicy().hasHeightForWidth())
        self.Mode4in1.setSizePolicy(sizePolicy)
        self.Mode4in1.setObjectName(_fromUtf8("Mode4in1"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.submit_pushButton.setEnabled)
        QtCore.QObject.connect(self.start_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.info_textBrowser.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_2.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_3.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_4.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_6.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_7.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_8.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_10.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_11.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_12.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_14.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_15.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox1_16.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_2.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_3.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_4.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_6.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_7.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_8.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_10.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_11.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_12.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_14.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_15.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_1_16.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabWidget, self.Mode4in1)
        Form.setTabOrder(self.Mode4in1, self.start_pushButton)
        Form.setTabOrder(self.start_pushButton, self.sn_lineEdit_1_1)
        Form.setTabOrder(self.sn_lineEdit_1_1, self.sn_lineEdit_1_2)
        Form.setTabOrder(self.sn_lineEdit_1_2, self.sn_lineEdit_1_3)
        Form.setTabOrder(self.sn_lineEdit_1_3, self.sn_lineEdit_1_4)
        Form.setTabOrder(self.sn_lineEdit_1_4, self.sn_lineEdit_1_5)
        Form.setTabOrder(self.sn_lineEdit_1_5, self.sn_lineEdit_1_6)
        Form.setTabOrder(self.sn_lineEdit_1_6, self.sn_lineEdit_1_7)
        Form.setTabOrder(self.sn_lineEdit_1_7, self.sn_lineEdit_1_8)
        Form.setTabOrder(self.sn_lineEdit_1_8, self.sn_lineEdit_1_9)
        Form.setTabOrder(self.sn_lineEdit_1_9, self.sn_lineEdit_1_10)
        Form.setTabOrder(self.sn_lineEdit_1_10, self.sn_lineEdit_1_11)
        Form.setTabOrder(self.sn_lineEdit_1_11, self.sn_lineEdit_1_12)
        Form.setTabOrder(self.sn_lineEdit_1_12, self.sn_lineEdit_1_13)
        Form.setTabOrder(self.sn_lineEdit_1_13, self.sn_lineEdit_1_14)
        Form.setTabOrder(self.sn_lineEdit_1_14, self.sn_lineEdit_1_15)
        Form.setTabOrder(self.sn_lineEdit_1_15, self.sn_lineEdit_1_16)
        Form.setTabOrder(self.sn_lineEdit_1_16, self.info_textBrowser)
        Form.setTabOrder(self.info_textBrowser, self.partNum_comboBox)
        Form.setTabOrder(self.partNum_comboBox, self.revision_comboBox)
        Form.setTabOrder(self.revision_comboBox, self.test_item_tableView)
        Form.setTabOrder(self.test_item_tableView, self.submit_pushButton)
        Form.setTabOrder(self.submit_pushButton, self.checkBox)
        Form.setTabOrder(self.checkBox, self.search_lineEdit)
        Form.setTabOrder(self.search_lineEdit, self.search_pushButton)
        Form.setTabOrder(self.search_pushButton, self.log_tableView)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "AGIGA-UFT-TEST", None))
        self.groupBox1_8.setTitle(_translate("Form", "Slot #8", None))
        self.sn_lineEdit_1_8.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_8.setPlaceholderText(_translate("Form", "Cable_SN_8", None))
        self.BatterylineEdit_1_8.setPlaceholderText(_translate("Form", "Battery_SN_8", None))
        self.groupBox1_2.setTitle(_translate("Form", "Slot #2", None))
        self.sn_lineEdit_1_2.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_2.setPlaceholderText(_translate("Form", "Cable_SN_2", None))
        self.BatterylineEdit_1_2.setPlaceholderText(_translate("Form", "Battery_SN_2", None))
        self.groupBox1_3.setTitle(_translate("Form", "Slot #3", None))
        self.sn_lineEdit_1_3.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_3.setPlaceholderText(_translate("Form", "Cable_SN_3", None))
        self.BatterylineEdit_1_3.setPlaceholderText(_translate("Form", "Battery_SN_3", None))
        self.groupBox1_4.setTitle(_translate("Form", "Slot #4", None))
        self.sn_lineEdit_1_4.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_4.setPlaceholderText(_translate("Form", "Cable_SN_4", None))
        self.BatterylineEdit_1_4.setPlaceholderText(_translate("Form", "Battery_SN_4", None))
        self.groupBox1_5.setTitle(_translate("Form", "Slot #5", None))
        self.sn_lineEdit_1_5.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_5.setPlaceholderText(_translate("Form", "Cable_SN_5", None))
        self.BatterylineEdit_1_5.setPlaceholderText(_translate("Form", "Battery_SN_5", None))
        self.groupBox1_6.setTitle(_translate("Form", "Slot #6", None))
        self.sn_lineEdit_1_6.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_6.setPlaceholderText(_translate("Form", "Cable_SN_6", None))
        self.BatterylineEdit_1_6.setPlaceholderText(_translate("Form", "Battery_SN_6", None))
        self.groupBox1_1.setTitle(_translate("Form", "Slot #1", None))
        self.sn_lineEdit_1_1.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_1.setPlaceholderText(_translate("Form", "Cable_SN_1", None))
        self.BatterylineEdit_1_1.setPlaceholderText(_translate("Form", "Battery_SN_1", None))
        self.groupBox1_7.setTitle(_translate("Form", "Slot #7", None))
        self.sn_lineEdit_1_7.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_7.setPlaceholderText(_translate("Form", "Cable_SN_7", None))
        self.BatterylineEdit_1_7.setPlaceholderText(_translate("Form", "Battery_SN_7", None))
        self.groupBox1_16.setTitle(_translate("Form", "Slot #16", None))
        self.sn_lineEdit_1_16.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_16.setPlaceholderText(_translate("Form", "Cable_SN_16", None))
        self.BatterylineEdit_1_16.setPlaceholderText(_translate("Form", "Battery_SN_16", None))
        self.groupBox1_9.setTitle(_translate("Form", "Slot #9", None))
        self.sn_lineEdit_1_9.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_9.setPlaceholderText(_translate("Form", "Cable_SN_9", None))
        self.BatterylineEdit_1_9.setPlaceholderText(_translate("Form", "Battery_SN_9", None))
        self.groupBox1_11.setTitle(_translate("Form", "Slot #11", None))
        self.sn_lineEdit_1_11.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_11.setPlaceholderText(_translate("Form", "Cable_SN_11", None))
        self.BatterylineEdit_1_11.setPlaceholderText(_translate("Form", "Battery_SN_11", None))
        self.groupBox1_12.setTitle(_translate("Form", "Slot #12", None))
        self.sn_lineEdit_1_12.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_12.setPlaceholderText(_translate("Form", "Cable_SN_12", None))
        self.BatterylineEdit_1_12.setPlaceholderText(_translate("Form", "Battery_SN_12", None))
        self.groupBox1_13.setTitle(_translate("Form", "Slot #13", None))
        self.sn_lineEdit_1_13.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_13.setPlaceholderText(_translate("Form", "Cable_SN_13", None))
        self.BatterylineEdit_1_13.setPlaceholderText(_translate("Form", "Battery_SN_13", None))
        self.groupBox1_10.setTitle(_translate("Form", "Slot #10", None))
        self.sn_lineEdit_1_10.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_10.setPlaceholderText(_translate("Form", "Cable_SN_10", None))
        self.BatterylineEdit_1_10.setPlaceholderText(_translate("Form", "Battery_SN_10", None))
        self.groupBox1_14.setTitle(_translate("Form", "Slot #14", None))
        self.sn_lineEdit_1_14.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_14.setPlaceholderText(_translate("Form", "Cable_SN_14", None))
        self.BatterylineEdit_1_14.setPlaceholderText(_translate("Form", "Battery_SN_14", None))
        self.groupBox1_15.setTitle(_translate("Form", "Slot #15", None))
        self.sn_lineEdit_1_15.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1_15.setPlaceholderText(_translate("Form", "Cable_SN_15", None))
        self.BatterylineEdit_1_15.setPlaceholderText(_translate("Form", "Battery_SN_15", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EB1), _translate("Form", "Erie #1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EB2), _translate("Form", "Erie #2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EB3), _translate("Form", "Erie #3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EB4), _translate("Form", "Erie #4", None))
        self.groupBox_6.setTitle(_translate("Form", "info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info), _translate("Form", "test", None))
        self.label_PN.setText(_translate("Form", "Part Number: ", None))
        self.label_REV.setText(_translate("Form", "Revision: ", None))
        self.label_DES.setText(_translate("Form", "Description: ", None))
        self.submit_pushButton.setText(_translate("Form", "submit", None))
        self.checkBox.setText(_translate("Form", "EditMode", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configuration), _translate("Form", "configuration", None))
        self.search_lineEdit.setPlaceholderText(_translate("Form", "search by serial number", None))
        self.search_pushButton.setText(_translate("Form", "Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "test log", None))
        self.title_label.setText(_translate("Form", "AGIGA UPGEM UFT V5.4.0", None))
        self.start_pushButton.setText(_translate("Form", "START", None))
        self.Mode4in1.setText(_translate("Form", "4 in 1", None))

