# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UFT_Ui.ui'
#
# Created: Tue Nov 07 12:24:26 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(970, 770)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 951, 701))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_EB1 = QtGui.QWidget()
        self.tab_EB1.setObjectName(_fromUtf8("tab_EB1"))
        self.groupBox8 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox8.setGeometry(QtCore.QRect(10, 590, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox8.sizePolicy().hasHeightForWidth())
        self.groupBox8.setSizePolicy(sizePolicy)
        self.groupBox8.setObjectName(_fromUtf8("groupBox8"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox8)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.sn_lineEdit_8 = QtGui.QLineEdit(self.groupBox8)
        self.sn_lineEdit_8.setMaxLength(33)
        self.sn_lineEdit_8.setObjectName(_fromUtf8("sn_lineEdit_8"))
        self.gridLayout_11.addWidget(self.sn_lineEdit_8, 0, 0, 1, 1)
        self.CablelineEdit_8 = QtGui.QLineEdit(self.groupBox8)
        self.CablelineEdit_8.setObjectName(_fromUtf8("CablelineEdit_8"))
        self.gridLayout_11.addWidget(self.CablelineEdit_8, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_11.addWidget(self.label_8, 1, 0, 1, 1)
        self.BatterylineEdit_8 = QtGui.QLineEdit(self.groupBox8)
        self.BatterylineEdit_8.setObjectName(_fromUtf8("BatterylineEdit_8"))
        self.gridLayout_11.addWidget(self.BatterylineEdit_8, 1, 1, 1, 1)
        self.groupBox2 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox2.setGeometry(QtCore.QRect(10, 90, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sn_lineEdit_2 = QtGui.QLineEdit(self.groupBox2)
        self.sn_lineEdit_2.setMaxLength(33)
        self.sn_lineEdit_2.setObjectName(_fromUtf8("sn_lineEdit_2"))
        self.gridLayout_2.addWidget(self.sn_lineEdit_2, 0, 0, 1, 1)
        self.CablelineEdit_2 = QtGui.QLineEdit(self.groupBox2)
        self.CablelineEdit_2.setObjectName(_fromUtf8("CablelineEdit_2"))
        self.gridLayout_2.addWidget(self.CablelineEdit_2, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.BatterylineEdit_2 = QtGui.QLineEdit(self.groupBox2)
        self.BatterylineEdit_2.setObjectName(_fromUtf8("BatterylineEdit_2"))
        self.gridLayout_2.addWidget(self.BatterylineEdit_2, 1, 1, 1, 1)
        self.groupBox3 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox3.setGeometry(QtCore.QRect(10, 170, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3.sizePolicy().hasHeightForWidth())
        self.groupBox3.setSizePolicy(sizePolicy)
        self.groupBox3.setObjectName(_fromUtf8("groupBox3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.sn_lineEdit_3 = QtGui.QLineEdit(self.groupBox3)
        self.sn_lineEdit_3.setMaxLength(33)
        self.sn_lineEdit_3.setObjectName(_fromUtf8("sn_lineEdit_3"))
        self.gridLayout_3.addWidget(self.sn_lineEdit_3, 0, 0, 1, 1)
        self.CablelineEdit_3 = QtGui.QLineEdit(self.groupBox3)
        self.CablelineEdit_3.setObjectName(_fromUtf8("CablelineEdit_3"))
        self.gridLayout_3.addWidget(self.CablelineEdit_3, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.BatterylineEdit_3 = QtGui.QLineEdit(self.groupBox3)
        self.BatterylineEdit_3.setObjectName(_fromUtf8("BatterylineEdit_3"))
        self.gridLayout_3.addWidget(self.BatterylineEdit_3, 1, 1, 1, 1)
        self.groupBox4 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox4.setGeometry(QtCore.QRect(10, 250, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox4.sizePolicy().hasHeightForWidth())
        self.groupBox4.setSizePolicy(sizePolicy)
        self.groupBox4.setObjectName(_fromUtf8("groupBox4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.sn_lineEdit_4 = QtGui.QLineEdit(self.groupBox4)
        self.sn_lineEdit_4.setMaxLength(33)
        self.sn_lineEdit_4.setObjectName(_fromUtf8("sn_lineEdit_4"))
        self.gridLayout_6.addWidget(self.sn_lineEdit_4, 0, 0, 1, 1)
        self.CablelineEdit_4 = QtGui.QLineEdit(self.groupBox4)
        self.CablelineEdit_4.setObjectName(_fromUtf8("CablelineEdit_4"))
        self.gridLayout_6.addWidget(self.CablelineEdit_4, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.BatterylineEdit_4 = QtGui.QLineEdit(self.groupBox4)
        self.BatterylineEdit_4.setObjectName(_fromUtf8("BatterylineEdit_4"))
        self.gridLayout_6.addWidget(self.BatterylineEdit_4, 1, 1, 1, 1)
        self.groupBox5 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox5.setGeometry(QtCore.QRect(10, 350, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox5.sizePolicy().hasHeightForWidth())
        self.groupBox5.setSizePolicy(sizePolicy)
        self.groupBox5.setObjectName(_fromUtf8("groupBox5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.sn_lineEdit_5 = QtGui.QLineEdit(self.groupBox5)
        self.sn_lineEdit_5.setAcceptDrops(True)
        self.sn_lineEdit_5.setText(_fromUtf8(""))
        self.sn_lineEdit_5.setMaxLength(33)
        self.sn_lineEdit_5.setObjectName(_fromUtf8("sn_lineEdit_5"))
        self.gridLayout_7.addWidget(self.sn_lineEdit_5, 0, 0, 1, 1)
        self.CablelineEdit_5 = QtGui.QLineEdit(self.groupBox5)
        self.CablelineEdit_5.setObjectName(_fromUtf8("CablelineEdit_5"))
        self.gridLayout_7.addWidget(self.CablelineEdit_5, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.BatterylineEdit_5 = QtGui.QLineEdit(self.groupBox5)
        self.BatterylineEdit_5.setObjectName(_fromUtf8("BatterylineEdit_5"))
        self.gridLayout_7.addWidget(self.BatterylineEdit_5, 1, 1, 1, 1)
        self.groupBox6 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox6.setGeometry(QtCore.QRect(10, 430, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox6.sizePolicy().hasHeightForWidth())
        self.groupBox6.setSizePolicy(sizePolicy)
        self.groupBox6.setObjectName(_fromUtf8("groupBox6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.sn_lineEdit_6 = QtGui.QLineEdit(self.groupBox6)
        self.sn_lineEdit_6.setMaxLength(33)
        self.sn_lineEdit_6.setObjectName(_fromUtf8("sn_lineEdit_6"))
        self.gridLayout_8.addWidget(self.sn_lineEdit_6, 0, 0, 1, 1)
        self.CablelineEdit_6 = QtGui.QLineEdit(self.groupBox6)
        self.CablelineEdit_6.setObjectName(_fromUtf8("CablelineEdit_6"))
        self.gridLayout_8.addWidget(self.CablelineEdit_6, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_8.addWidget(self.label_6, 1, 0, 1, 1)
        self.BatterylineEdit_6 = QtGui.QLineEdit(self.groupBox6)
        self.BatterylineEdit_6.setObjectName(_fromUtf8("BatterylineEdit_6"))
        self.gridLayout_8.addWidget(self.BatterylineEdit_6, 1, 1, 1, 1)
        self.groupBox1 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox1.setGeometry(QtCore.QRect(10, 10, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sn_lineEdit_1 = QtGui.QLineEdit(self.groupBox1)
        self.sn_lineEdit_1.setAcceptDrops(True)
        self.sn_lineEdit_1.setText(_fromUtf8(""))
        self.sn_lineEdit_1.setMaxLength(33)
        self.sn_lineEdit_1.setObjectName(_fromUtf8("sn_lineEdit_1"))
        self.gridLayout.addWidget(self.sn_lineEdit_1, 0, 0, 1, 1)
        self.CablelineEdit_1 = QtGui.QLineEdit(self.groupBox1)
        self.CablelineEdit_1.setObjectName(_fromUtf8("CablelineEdit_1"))
        self.gridLayout.addWidget(self.CablelineEdit_1, 0, 1, 1, 1)
        self.label_1 = QtGui.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setText(_fromUtf8(""))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1)
        self.BatterylineEdit_1 = QtGui.QLineEdit(self.groupBox1)
        self.BatterylineEdit_1.setObjectName(_fromUtf8("BatterylineEdit_1"))
        self.gridLayout.addWidget(self.BatterylineEdit_1, 1, 1, 1, 1)
        self.groupBox7 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox7.setGeometry(QtCore.QRect(10, 510, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox7.sizePolicy().hasHeightForWidth())
        self.groupBox7.setSizePolicy(sizePolicy)
        self.groupBox7.setObjectName(_fromUtf8("groupBox7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.sn_lineEdit_7 = QtGui.QLineEdit(self.groupBox7)
        self.sn_lineEdit_7.setMaxLength(33)
        self.sn_lineEdit_7.setObjectName(_fromUtf8("sn_lineEdit_7"))
        self.gridLayout_10.addWidget(self.sn_lineEdit_7, 0, 0, 1, 1)
        self.CablelineEdit_7 = QtGui.QLineEdit(self.groupBox7)
        self.CablelineEdit_7.setObjectName(_fromUtf8("CablelineEdit_7"))
        self.gridLayout_10.addWidget(self.CablelineEdit_7, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_10.addWidget(self.label_7, 1, 0, 1, 1)
        self.BatterylineEdit_7 = QtGui.QLineEdit(self.groupBox7)
        self.BatterylineEdit_7.setObjectName(_fromUtf8("BatterylineEdit_7"))
        self.gridLayout_10.addWidget(self.BatterylineEdit_7, 1, 1, 1, 1)
        self.groupBox16 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox16.setGeometry(QtCore.QRect(480, 590, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox16.sizePolicy().hasHeightForWidth())
        self.groupBox16.setSizePolicy(sizePolicy)
        self.groupBox16.setObjectName(_fromUtf8("groupBox16"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox16)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.sn_lineEdit_16 = QtGui.QLineEdit(self.groupBox16)
        self.sn_lineEdit_16.setMaxLength(33)
        self.sn_lineEdit_16.setObjectName(_fromUtf8("sn_lineEdit_16"))
        self.gridLayout_19.addWidget(self.sn_lineEdit_16, 0, 0, 1, 1)
        self.CablelineEdit_16 = QtGui.QLineEdit(self.groupBox16)
        self.CablelineEdit_16.setObjectName(_fromUtf8("CablelineEdit_16"))
        self.gridLayout_19.addWidget(self.CablelineEdit_16, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_19.addWidget(self.label_16, 1, 0, 1, 1)
        self.BatterylineEdit_16 = QtGui.QLineEdit(self.groupBox16)
        self.BatterylineEdit_16.setObjectName(_fromUtf8("BatterylineEdit_16"))
        self.gridLayout_19.addWidget(self.BatterylineEdit_16, 1, 1, 1, 1)
        self.groupBox9 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox9.setGeometry(QtCore.QRect(480, 10, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox9.sizePolicy().hasHeightForWidth())
        self.groupBox9.setSizePolicy(sizePolicy)
        self.groupBox9.setObjectName(_fromUtf8("groupBox9"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox9)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.sn_lineEdit_9 = QtGui.QLineEdit(self.groupBox9)
        self.sn_lineEdit_9.setAcceptDrops(True)
        self.sn_lineEdit_9.setText(_fromUtf8(""))
        self.sn_lineEdit_9.setMaxLength(33)
        self.sn_lineEdit_9.setObjectName(_fromUtf8("sn_lineEdit_9"))
        self.gridLayout_12.addWidget(self.sn_lineEdit_9, 0, 0, 1, 1)
        self.CablelineEdit_9 = QtGui.QLineEdit(self.groupBox9)
        self.CablelineEdit_9.setObjectName(_fromUtf8("CablelineEdit_9"))
        self.gridLayout_12.addWidget(self.CablelineEdit_9, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_12.addWidget(self.label_9, 1, 0, 1, 1)
        self.BatterylineEdit_9 = QtGui.QLineEdit(self.groupBox9)
        self.BatterylineEdit_9.setObjectName(_fromUtf8("BatterylineEdit_9"))
        self.gridLayout_12.addWidget(self.BatterylineEdit_9, 1, 1, 1, 1)
        self.groupBox11 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox11.setGeometry(QtCore.QRect(480, 170, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox11.sizePolicy().hasHeightForWidth())
        self.groupBox11.setSizePolicy(sizePolicy)
        self.groupBox11.setObjectName(_fromUtf8("groupBox11"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox11)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.sn_lineEdit_11 = QtGui.QLineEdit(self.groupBox11)
        self.sn_lineEdit_11.setMaxLength(33)
        self.sn_lineEdit_11.setObjectName(_fromUtf8("sn_lineEdit_11"))
        self.gridLayout_14.addWidget(self.sn_lineEdit_11, 0, 0, 1, 1)
        self.CablelineEdit_11 = QtGui.QLineEdit(self.groupBox11)
        self.CablelineEdit_11.setObjectName(_fromUtf8("CablelineEdit_11"))
        self.gridLayout_14.addWidget(self.CablelineEdit_11, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_14.addWidget(self.label_11, 1, 0, 1, 1)
        self.BatterylineEdit_11 = QtGui.QLineEdit(self.groupBox11)
        self.BatterylineEdit_11.setObjectName(_fromUtf8("BatterylineEdit_11"))
        self.gridLayout_14.addWidget(self.BatterylineEdit_11, 1, 1, 1, 1)
        self.groupBox12 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox12.setGeometry(QtCore.QRect(480, 250, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox12.sizePolicy().hasHeightForWidth())
        self.groupBox12.setSizePolicy(sizePolicy)
        self.groupBox12.setObjectName(_fromUtf8("groupBox12"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox12)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.sn_lineEdit_12 = QtGui.QLineEdit(self.groupBox12)
        self.sn_lineEdit_12.setMaxLength(33)
        self.sn_lineEdit_12.setObjectName(_fromUtf8("sn_lineEdit_12"))
        self.gridLayout_15.addWidget(self.sn_lineEdit_12, 0, 0, 1, 1)
        self.CablelineEdit_12 = QtGui.QLineEdit(self.groupBox12)
        self.CablelineEdit_12.setObjectName(_fromUtf8("CablelineEdit_12"))
        self.gridLayout_15.addWidget(self.CablelineEdit_12, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_15.addWidget(self.label_12, 1, 0, 1, 1)
        self.BatterylineEdit_12 = QtGui.QLineEdit(self.groupBox12)
        self.BatterylineEdit_12.setObjectName(_fromUtf8("BatterylineEdit_12"))
        self.gridLayout_15.addWidget(self.BatterylineEdit_12, 1, 1, 1, 1)
        self.groupBox13 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox13.setGeometry(QtCore.QRect(480, 350, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox13.sizePolicy().hasHeightForWidth())
        self.groupBox13.setSizePolicy(sizePolicy)
        self.groupBox13.setObjectName(_fromUtf8("groupBox13"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox13)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.sn_lineEdit_13 = QtGui.QLineEdit(self.groupBox13)
        self.sn_lineEdit_13.setAcceptDrops(True)
        self.sn_lineEdit_13.setText(_fromUtf8(""))
        self.sn_lineEdit_13.setMaxLength(33)
        self.sn_lineEdit_13.setObjectName(_fromUtf8("sn_lineEdit_13"))
        self.gridLayout_16.addWidget(self.sn_lineEdit_13, 0, 0, 1, 1)
        self.CablelineEdit_13 = QtGui.QLineEdit(self.groupBox13)
        self.CablelineEdit_13.setObjectName(_fromUtf8("CablelineEdit_13"))
        self.gridLayout_16.addWidget(self.CablelineEdit_13, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_16.addWidget(self.label_13, 1, 0, 1, 1)
        self.BatterylineEdit_13 = QtGui.QLineEdit(self.groupBox13)
        self.BatterylineEdit_13.setObjectName(_fromUtf8("BatterylineEdit_13"))
        self.gridLayout_16.addWidget(self.BatterylineEdit_13, 1, 1, 1, 1)
        self.groupBox10 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox10.setGeometry(QtCore.QRect(480, 90, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox10.sizePolicy().hasHeightForWidth())
        self.groupBox10.setSizePolicy(sizePolicy)
        self.groupBox10.setObjectName(_fromUtf8("groupBox10"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox10)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.sn_lineEdit_10 = QtGui.QLineEdit(self.groupBox10)
        self.sn_lineEdit_10.setMaxLength(33)
        self.sn_lineEdit_10.setObjectName(_fromUtf8("sn_lineEdit_10"))
        self.gridLayout_13.addWidget(self.sn_lineEdit_10, 0, 0, 1, 1)
        self.CablelineEdit_10 = QtGui.QLineEdit(self.groupBox10)
        self.CablelineEdit_10.setObjectName(_fromUtf8("CablelineEdit_10"))
        self.gridLayout_13.addWidget(self.CablelineEdit_10, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_13.addWidget(self.label_10, 1, 0, 1, 1)
        self.BatterylineEdit_10 = QtGui.QLineEdit(self.groupBox10)
        self.BatterylineEdit_10.setObjectName(_fromUtf8("BatterylineEdit_10"))
        self.gridLayout_13.addWidget(self.BatterylineEdit_10, 1, 1, 1, 1)
        self.groupBox14 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox14.setGeometry(QtCore.QRect(480, 430, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox14.sizePolicy().hasHeightForWidth())
        self.groupBox14.setSizePolicy(sizePolicy)
        self.groupBox14.setObjectName(_fromUtf8("groupBox14"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox14)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.sn_lineEdit_14 = QtGui.QLineEdit(self.groupBox14)
        self.sn_lineEdit_14.setMaxLength(33)
        self.sn_lineEdit_14.setObjectName(_fromUtf8("sn_lineEdit_14"))
        self.gridLayout_17.addWidget(self.sn_lineEdit_14, 0, 0, 1, 1)
        self.CablelineEdit_14 = QtGui.QLineEdit(self.groupBox14)
        self.CablelineEdit_14.setObjectName(_fromUtf8("CablelineEdit_14"))
        self.gridLayout_17.addWidget(self.CablelineEdit_14, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_17.addWidget(self.label_14, 1, 0, 1, 1)
        self.BatterylineEdit_14 = QtGui.QLineEdit(self.groupBox14)
        self.BatterylineEdit_14.setObjectName(_fromUtf8("BatterylineEdit_14"))
        self.gridLayout_17.addWidget(self.BatterylineEdit_14, 1, 1, 1, 1)
        self.groupBox15 = QtGui.QGroupBox(self.tab_EB1)
        self.groupBox15.setGeometry(QtCore.QRect(480, 510, 451, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox15.sizePolicy().hasHeightForWidth())
        self.groupBox15.setSizePolicy(sizePolicy)
        self.groupBox15.setObjectName(_fromUtf8("groupBox15"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox15)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.sn_lineEdit_15 = QtGui.QLineEdit(self.groupBox15)
        self.sn_lineEdit_15.setMaxLength(33)
        self.sn_lineEdit_15.setObjectName(_fromUtf8("sn_lineEdit_15"))
        self.gridLayout_18.addWidget(self.sn_lineEdit_15, 0, 0, 1, 1)
        self.CablelineEdit_15 = QtGui.QLineEdit(self.groupBox15)
        self.CablelineEdit_15.setObjectName(_fromUtf8("CablelineEdit_15"))
        self.gridLayout_18.addWidget(self.CablelineEdit_15, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox15)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_18.addWidget(self.label_15, 1, 0, 1, 1)
        self.BatterylineEdit_15 = QtGui.QLineEdit(self.groupBox15)
        self.BatterylineEdit_15.setObjectName(_fromUtf8("BatterylineEdit_15"))
        self.gridLayout_18.addWidget(self.BatterylineEdit_15, 1, 1, 1, 1)
        self.line = QtGui.QFrame(self.tab_EB1)
        self.line.setGeometry(QtCore.QRect(10, 330, 921, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab_EB1)
        self.line_2.setGeometry(QtCore.QRect(460, 20, 20, 651))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tabWidget.addTab(self.tab_EB1, _fromUtf8(""))
        self.tab_EB2 = QtGui.QWidget()
        self.tab_EB2.setObjectName(_fromUtf8("tab_EB2"))
        self.tabWidget.addTab(self.tab_EB2, _fromUtf8(""))
        self.tab_EB3 = QtGui.QWidget()
        self.tab_EB3.setObjectName(_fromUtf8("tab_EB3"))
        self.tabWidget.addTab(self.tab_EB3, _fromUtf8(""))
        self.tab_EB4 = QtGui.QWidget()
        self.tab_EB4.setObjectName(_fromUtf8("tab_EB4"))
        self.tabWidget.addTab(self.tab_EB4, _fromUtf8(""))
        self.info = QtGui.QWidget()
        self.info.setObjectName(_fromUtf8("info"))
        self.groupBox_6 = QtGui.QGroupBox(self.info)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 931, 661))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.info_textBrowser = QtGui.QTextBrowser(self.groupBox_6)
        self.info_textBrowser.setGeometry(QtCore.QRect(10, 20, 911, 631))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_textBrowser.sizePolicy().hasHeightForWidth())
        self.info_textBrowser.setSizePolicy(sizePolicy)
        self.info_textBrowser.setAutoFillBackground(True)
        self.info_textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.info_textBrowser.setObjectName(_fromUtf8("info_textBrowser"))
        self.tabWidget.addTab(self.info, _fromUtf8(""))
        self.configuration = QtGui.QWidget()
        self.configuration.setObjectName(_fromUtf8("configuration"))
        self.gridLayout_9 = QtGui.QGridLayout(self.configuration)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.partNum_comboBox = QtGui.QComboBox(self.configuration)
        self.partNum_comboBox.setObjectName(_fromUtf8("partNum_comboBox"))
        self.gridLayout_4.addWidget(self.partNum_comboBox, 1, 0, 1, 1)
        self.label_PN = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_PN.setFont(font)
        self.label_PN.setObjectName(_fromUtf8("label_PN"))
        self.gridLayout_4.addWidget(self.label_PN, 0, 0, 1, 1)
        self.label_REV = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_REV.setFont(font)
        self.label_REV.setObjectName(_fromUtf8("label_REV"))
        self.gridLayout_4.addWidget(self.label_REV, 0, 1, 1, 1)
        self.revision_comboBox = QtGui.QComboBox(self.configuration)
        self.revision_comboBox.setObjectName(_fromUtf8("revision_comboBox"))
        self.gridLayout_4.addWidget(self.revision_comboBox, 1, 1, 1, 1)
        self.label_DES = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label_DES.setFont(font)
        self.label_DES.setObjectName(_fromUtf8("label_DES"))
        self.gridLayout_4.addWidget(self.label_DES, 0, 2, 1, 1)
        self.descriptionLabel = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setText(_fromUtf8(""))
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.gridLayout_4.addWidget(self.descriptionLabel, 1, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.test_item_tableView = QtGui.QTableView(self.configuration)
        self.test_item_tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.test_item_tableView.setObjectName(_fromUtf8("test_item_tableView"))
        self.gridLayout_9.addWidget(self.test_item_tableView, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.submit_pushButton = QtGui.QPushButton(self.configuration)
        self.submit_pushButton.setEnabled(False)
        self.submit_pushButton.setObjectName(_fromUtf8("submit_pushButton"))
        self.horizontalLayout_5.addWidget(self.submit_pushButton)
        self.checkBox = QtGui.QCheckBox(self.configuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.tabWidget.addTab(self.configuration, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.search_lineEdit = QtGui.QLineEdit(self.tab)
        self.search_lineEdit.setInputMask(_fromUtf8(""))
        self.search_lineEdit.setObjectName(_fromUtf8("search_lineEdit"))
        self.horizontalLayout_2.addWidget(self.search_lineEdit)
        self.search_pushButton = QtGui.QPushButton(self.tab)
        self.search_pushButton.setObjectName(_fromUtf8("search_pushButton"))
        self.horizontalLayout_2.addWidget(self.search_pushButton)
        self.search_result_label = QtGui.QLabel(self.tab)
        self.search_result_label.setText(_fromUtf8(""))
        self.search_result_label.setObjectName(_fromUtf8("search_result_label"))
        self.horizontalLayout_2.addWidget(self.search_result_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.log_tableView = QtGui.QTableView(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_tableView.sizePolicy().hasHeightForWidth())
        self.log_tableView.setSizePolicy(sizePolicy)
        self.log_tableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.log_tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.log_tableView.setObjectName(_fromUtf8("log_tableView"))
        self.gridLayout_5.addWidget(self.log_tableView, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.title_label = QtGui.QLabel(Form)
        self.title_label.setGeometry(QtCore.QRect(20, 5, 311, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andalus"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAutoFillBackground(False)
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 740, 951, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.lcdNumber = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout_4.addWidget(self.lcdNumber)
        self.start_pushButton = QtGui.QPushButton(Form)
        self.start_pushButton.setGeometry(QtCore.QRect(750, 5, 161, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_pushButton.sizePolicy().hasHeightForWidth())
        self.start_pushButton.setSizePolicy(sizePolicy)
        self.start_pushButton.setObjectName(_fromUtf8("start_pushButton"))
        self.Mode4in1 = QtGui.QCheckBox(Form)
        self.Mode4in1.setGeometry(QtCore.QRect(580, 30, 67, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mode4in1.sizePolicy().hasHeightForWidth())
        self.Mode4in1.setSizePolicy(sizePolicy)
        self.Mode4in1.setObjectName(_fromUtf8("Mode4in1"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.submit_pushButton.setEnabled)
        QtCore.QObject.connect(self.start_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.info_textBrowser.clear)
        QtCore.QObject.connect(self.sn_lineEdit_1, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_2.clear)
        QtCore.QObject.connect(self.sn_lineEdit_2, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_3.clear)
        QtCore.QObject.connect(self.sn_lineEdit_3, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_4.clear)
        QtCore.QObject.connect(self.sn_lineEdit_4, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_5.clear)
        QtCore.QObject.connect(self.sn_lineEdit_5, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_6.clear)
        QtCore.QObject.connect(self.sn_lineEdit_6, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_7.clear)
        QtCore.QObject.connect(self.sn_lineEdit_7, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_8.clear)
        QtCore.QObject.connect(self.sn_lineEdit_8, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_9.clear)
        QtCore.QObject.connect(self.sn_lineEdit_9, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_10.clear)
        QtCore.QObject.connect(self.sn_lineEdit_10, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_11.clear)
        QtCore.QObject.connect(self.sn_lineEdit_11, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_12.clear)
        QtCore.QObject.connect(self.sn_lineEdit_12, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_13.clear)
        QtCore.QObject.connect(self.sn_lineEdit_13, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_14.clear)
        QtCore.QObject.connect(self.sn_lineEdit_14, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_15.clear)
        QtCore.QObject.connect(self.sn_lineEdit_15, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_16.clear)
        QtCore.QObject.connect(self.sn_lineEdit_1, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_2.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_2, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_3.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_3, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_4.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_4, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_5.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_5, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_6.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_6, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_7.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_7, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_8.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_8, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_9.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_9, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_10.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_10, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_11.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_11, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_12.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_12, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_13.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_13, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_14.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_14, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_15.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_15, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_16.setFocus)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox2.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox3.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox4.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox6.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox7.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox8.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox10.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox11.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox12.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox14.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox15.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox16.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_2.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_3.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_4.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_6.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_7.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_8.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_10.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_11.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_12.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_14.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_15.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_16.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabWidget, self.Mode4in1)
        Form.setTabOrder(self.Mode4in1, self.start_pushButton)
        Form.setTabOrder(self.start_pushButton, self.sn_lineEdit_1)
        Form.setTabOrder(self.sn_lineEdit_1, self.sn_lineEdit_2)
        Form.setTabOrder(self.sn_lineEdit_2, self.sn_lineEdit_3)
        Form.setTabOrder(self.sn_lineEdit_3, self.sn_lineEdit_4)
        Form.setTabOrder(self.sn_lineEdit_4, self.sn_lineEdit_5)
        Form.setTabOrder(self.sn_lineEdit_5, self.sn_lineEdit_6)
        Form.setTabOrder(self.sn_lineEdit_6, self.sn_lineEdit_7)
        Form.setTabOrder(self.sn_lineEdit_7, self.sn_lineEdit_8)
        Form.setTabOrder(self.sn_lineEdit_8, self.sn_lineEdit_9)
        Form.setTabOrder(self.sn_lineEdit_9, self.sn_lineEdit_10)
        Form.setTabOrder(self.sn_lineEdit_10, self.sn_lineEdit_11)
        Form.setTabOrder(self.sn_lineEdit_11, self.sn_lineEdit_12)
        Form.setTabOrder(self.sn_lineEdit_12, self.sn_lineEdit_13)
        Form.setTabOrder(self.sn_lineEdit_13, self.sn_lineEdit_14)
        Form.setTabOrder(self.sn_lineEdit_14, self.sn_lineEdit_15)
        Form.setTabOrder(self.sn_lineEdit_15, self.sn_lineEdit_16)
        Form.setTabOrder(self.sn_lineEdit_16, self.info_textBrowser)
        Form.setTabOrder(self.info_textBrowser, self.partNum_comboBox)
        Form.setTabOrder(self.partNum_comboBox, self.revision_comboBox)
        Form.setTabOrder(self.revision_comboBox, self.test_item_tableView)
        Form.setTabOrder(self.test_item_tableView, self.submit_pushButton)
        Form.setTabOrder(self.submit_pushButton, self.checkBox)
        Form.setTabOrder(self.checkBox, self.search_lineEdit)
        Form.setTabOrder(self.search_lineEdit, self.search_pushButton)
        Form.setTabOrder(self.search_pushButton, self.log_tableView)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "AGIGA-UFT-TEST", None))
        self.groupBox8.setTitle(_translate("Form", "Slot #8", None))
        self.sn_lineEdit_8.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_8.setPlaceholderText(_translate("Form", "Cable_SN_8", None))
        self.BatterylineEdit_8.setPlaceholderText(_translate("Form", "Battery_SN_8", None))
        self.groupBox2.setTitle(_translate("Form", "Slot #2", None))
        self.sn_lineEdit_2.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_2.setPlaceholderText(_translate("Form", "Cable_SN_2", None))
        self.BatterylineEdit_2.setPlaceholderText(_translate("Form", "Battery_SN_2", None))
        self.groupBox3.setTitle(_translate("Form", "Slot #3", None))
        self.sn_lineEdit_3.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_3.setPlaceholderText(_translate("Form", "Cable_SN_3", None))
        self.BatterylineEdit_3.setPlaceholderText(_translate("Form", "Battery_SN_3", None))
        self.groupBox4.setTitle(_translate("Form", "Slot #4", None))
        self.sn_lineEdit_4.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_4.setPlaceholderText(_translate("Form", "Cable_SN_4", None))
        self.BatterylineEdit_4.setPlaceholderText(_translate("Form", "Battery_SN_4", None))
        self.groupBox5.setTitle(_translate("Form", "Slot #5", None))
        self.sn_lineEdit_5.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_5.setPlaceholderText(_translate("Form", "Cable_SN_5", None))
        self.BatterylineEdit_5.setPlaceholderText(_translate("Form", "Battery_SN_5", None))
        self.groupBox6.setTitle(_translate("Form", "Slot #6", None))
        self.sn_lineEdit_6.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_6.setPlaceholderText(_translate("Form", "Cable_SN_6", None))
        self.BatterylineEdit_6.setPlaceholderText(_translate("Form", "Battery_SN_6", None))
        self.groupBox1.setTitle(_translate("Form", "Slot #1", None))
        self.sn_lineEdit_1.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_1.setPlaceholderText(_translate("Form", "Cable_SN_1", None))
        self.BatterylineEdit_1.setPlaceholderText(_translate("Form", "Battery_SN_1", None))
        self.groupBox7.setTitle(_translate("Form", "Slot #7", None))
        self.sn_lineEdit_7.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_7.setPlaceholderText(_translate("Form", "Cable_SN_7", None))
        self.BatterylineEdit_7.setPlaceholderText(_translate("Form", "Battery_SN_7", None))
        self.groupBox16.setTitle(_translate("Form", "Slot #16", None))
        self.sn_lineEdit_16.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_16.setPlaceholderText(_translate("Form", "Cable_SN_16", None))
        self.BatterylineEdit_16.setPlaceholderText(_translate("Form", "Battery_SN_16", None))
        self.groupBox9.setTitle(_translate("Form", "Slot #9", None))
        self.sn_lineEdit_9.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_9.setPlaceholderText(_translate("Form", "Cable_SN_9", None))
        self.BatterylineEdit_9.setPlaceholderText(_translate("Form", "Battery_SN_9", None))
        self.groupBox11.setTitle(_translate("Form", "Slot #11", None))
        self.sn_lineEdit_11.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_11.setPlaceholderText(_translate("Form", "Cable_SN_11", None))
        self.BatterylineEdit_11.setPlaceholderText(_translate("Form", "Battery_SN_11", None))
        self.groupBox12.setTitle(_translate("Form", "Slot #12", None))
        self.sn_lineEdit_12.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_12.setPlaceholderText(_translate("Form", "Cable_SN_12", None))
        self.BatterylineEdit_12.setPlaceholderText(_translate("Form", "Battery_SN_12", None))
        self.groupBox13.setTitle(_translate("Form", "Slot #13", None))
        self.sn_lineEdit_13.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_13.setPlaceholderText(_translate("Form", "Cable_SN_13", None))
        self.BatterylineEdit_13.setPlaceholderText(_translate("Form", "Battery_SN_13", None))
        self.groupBox10.setTitle(_translate("Form", "Slot #10", None))
        self.sn_lineEdit_10.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_10.setPlaceholderText(_translate("Form", "Cable_SN_10", None))
        self.BatterylineEdit_10.setPlaceholderText(_translate("Form", "Battery_SN_10", None))
        self.groupBox14.setTitle(_translate("Form", "Slot #14", None))
        self.sn_lineEdit_14.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_14.setPlaceholderText(_translate("Form", "Cable_SN_14", None))
        self.BatterylineEdit_14.setPlaceholderText(_translate("Form", "Battery_SN_14", None))
        self.groupBox15.setTitle(_translate("Form", "Slot #15", None))
        self.sn_lineEdit_15.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.CablelineEdit_15.setPlaceholderText(_translate("Form", "Cable_SN_15", None))
        self.BatterylineEdit_15.setPlaceholderText(_translate("Form", "Battery_SN_15", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EB1), _translate("Form", "Erie #1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EB2), _translate("Form", "Erie #2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EB3), _translate("Form", "Erie #3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EB4), _translate("Form", "Erie #4", None))
        self.groupBox_6.setTitle(_translate("Form", "info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info), _translate("Form", "test", None))
        self.label_PN.setText(_translate("Form", "Part Number: ", None))
        self.label_REV.setText(_translate("Form", "Revision: ", None))
        self.label_DES.setText(_translate("Form", "Description: ", None))
        self.submit_pushButton.setText(_translate("Form", "submit", None))
        self.checkBox.setText(_translate("Form", "EditMode", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configuration), _translate("Form", "configuration", None))
        self.search_lineEdit.setPlaceholderText(_translate("Form", "search by serial number", None))
        self.search_pushButton.setText(_translate("Form", "Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "test log", None))
        self.title_label.setText(_translate("Form", "AGIGA UPGEM UFT V5.4.0", None))
        self.start_pushButton.setText(_translate("Form", "START", None))
        self.Mode4in1.setText(_translate("Form", "4 in 1", None))

